# Aggregator Configuration
# Controls score aggregation and stage mapping

aggregator:
  # Stage thresholds for score mapping (0-7 scale)
  stage_thresholds:
    - 2.5    # Threshold for Stage 0 -> Stage 1
    - 4.5    # Threshold for Stage 1 -> Stage 2  
    - 6.5    # Threshold for Stage 2 -> Stage 3
    
  # Default stage thresholds (backward compatibility)
  default_thresholds:
    - 2.5
    - 4.5
    - 6.5
    
  # Dimension mapping
  dimensions:
    mobility:
      terms:
        - "walking"
        - "balance"
        - "falls"
        - "mobility"
      weight: 1.0
      
    breathing:
      terms:
        - "breathing"
        - "respiratory"
        - "shortness of breath"
      weight: 1.0
      
    swallowing:
      terms:
        - "swallowing"
        - "choking"
        - "eating"
      weight: 1.0
      
    communication:
      terms:
        - "speech"
        - "communication"
        - "talking"
      weight: 1.0
      
  # Score calculation
  scoring:
    min_score: 0
    max_score: 7
    default_weight: 1.0
    
  # Logging
  logging:
    log_aggregation: true
    level: "INFO"